#!/usr/bin/python

# Examples:
#  trackrtool token
#  trackrtool list
#  trackrtool get  0000d446-3ac6fbc3
#  trackrtool create TestTracker2 Bluetooth 00000042-00000002 trackr
#  trackrtool set 00000042-00000002 50 44.44 55.99 1
#  trackrtool list
#  trackrtool delete 00000042-00000002

import trackr
import sys
import pprint
import os

cmd = sys.argv[1]

t = trackr.Trackr()
pp=pprint.PrettyPrinter(indent=4)


def getToken():
    try:
        token = os.environ["TRACKR_TOKEN"]
    except KeyError:
        token = None
    if not token:
        try:
            user=os.environ["TRACKR_USER"]
        except KeyError:
            print "Trackr username: ",
            user=sys.stdin.readline().rstrip("\n")
            print "\r",
        try:    
            password=os.environ["TRACKR_PASSWORD"]
        except KeyError:
            print "Trackr password: ",
            password=sys.stdin.readline().rstrip("\n")
            print "\r",
            print "Getting token for " + user
        token = t.getToken(user, password)
    return token

if cmd == "token":
    print(getToken())
elif cmd == "list":
    token = getToken()
    trackers=t.getTrackers(token)
    print("{:<20s} {:<20s} {:2s} {:8.5s} {:8.5s} {}".format(
        "Name", "TokenID", "Bat", "Lat","Long","Last Seen"));
    for tracker in trackers:
        print("{:<20s} {:<20s} {:2d}% {:8.5f} {:8.5f} {}".format(
            tracker['customName'],
            tracker['trackerId'],
            int(tracker['batteryLevel']),
            float(tracker['lastKnownLocation']['latitude']),
            float(tracker['lastKnownLocation']['longitude']),
            tracker['lastTimeSeen']))
elif cmd == "featurever":
    token = getToken()    
    print("{}".format(t.getFeatureVersion(token)))
elif cmd == "get":
    token = getToken()
    tracker=t.getTracker(token,sys.argv[2])
    for k in tracker:
        print("{}: {}".format(k, tracker[k]))
elif cmd == "set":
    id = sys.argv[2]
    bat = int(sys.argv[3])
    lat = float(sys.argv[4])
    lon = float(sys.argv[5])
    con = (int(sys.argv[6]) != 0)
        
    r=t.updateTracker(id, bat, lat, lon, con, 0)
    if r[0] == id:
        print("Success")
    else:
        print("Fail")
elif cmd == "create":
    token = getToken()
    name = sys.argv[2]
    type = sys.argv[3]
    id = sys.argv[4]
    icon = sys.argv[5]
    print(t.createItemWithTracker(token, name, type, id, icon, 0))
elif cmd == "delete":
    token = getToken()
    id = sys.argv[2]
    print(t.deleteTrackr(token, id, 0))
    
                                            
#
